ETAB
22KZN	01.05.1981	PROD	HLIQ  HWEF    BHPT 10 
22KZN	01.01.1987	INJE	HWAT  HWEF    BHPT 500 
--********************--
335	01.10.1983	PROD	HLIQ  HWEF    BHPT 10 
335	01.08.1984	INJE	HWAT  HWEF    BHPT 500 
--********************--
334	01.05.1984	PROD	HLIQ  HWEF    BHPT 10 
--********************--
32KZN	01.05.1981	PROD	HLIQ  HWEF    BHPT 10 
--********************--
336	01.07.1983	PROD	HLIQ  HWEF    BHPT 10 
--********************--
333	01.10.1984	PROD	HLIQ  HWEF    BHPT 10 
--********************--
344	01.01.1985	PROD	HLIQ  HWEF    BHPT 10 
--********************--
345	01.04.1984	PROD	HLIQ  HWEF    BHPT 10 
--********************--
346	01.07.1984	PROD	HLIQ  HWEF    BHPT 10 
--********************--
341	01.06.1983	PROD	HLIQ  HWEF    BHPT 10 
--********************--
337	01.03.1984	PROD	HLIQ  HWEF    BHPT 10 
--********************--
ENDE
