ETAB
61	01.03.1992	PROD	HLIQ  HWEF    BHPT 10 
--********************--
66	01.05.1992	PROD	HLIQ  HWEF    BHPT 10 
--********************--
20	01.06.1974	PROD	HLIQ  HWEF    BHPT 10 
--********************--
21	01.09.1973	PROD	HLIQ  HWEF    BHPT 10 
--********************--
4	01.08.1974	PROD	HLIQ  HWEF    BHPT 10 
4	01.01.1978	INJE	HWAT  HWEF    BHPT 500 
--********************--
6	01.09.1973	PROD	HLIQ  HWEF    BHPT 10 
--********************--
23A	01.03.1973	PROD	HLIQ  HWEF    BHPT 10 
--********************--
13	01.03.1969	PROD	HLIQ  HWEF    BHPT 10 
13	01.02.1979	INJE	HWAT  HWEF    BHPT 500 
--********************--
9	01.03.1969	PROD	HLIQ  HWEF    BHPT 10 
--********************--
58	01.03.1992	PROD	HLIQ  HWEF    BHPT 10 
--********************--
11	01.06.1973	PROD	HLIQ  HWEF    BHPT 10 
--********************--
14	01.01.1973	PROD	HLIQ  HWEF    BHPT 10 
--********************--
31	01.02.1974	PROD	HLIQ  HWEF    BHPT 10 
--********************--
ENDE
